apiVersion: hdfs.stackable.tech/v1alpha1
kind: HdfsCluster
metadata:
  name: hdfsc
spec:
  namenodeReplicas: 2
  datanodeReplicas: 3
  journalnodeReplicas: 3
  kerberos:
    realm: STACKABLE
    kdc: stackable-krb-kdc.kvm
