[package]
name = "zookeeper-operator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.5"
failure = "0.1.8"
futures = { version = "0.3.17", features = ["compat"] }
semver = "1.0.4"
serde = "1.0.130"
serde_json = "1.0.68"
serde_yaml = "0.8.21"
snafu = "0.6.10"
structopt = "0.3.23"
strum = "0.22.0"
strum_macros = "0.22.0"
tokio = { version = "1.12.0", features = ["full"] }
tokio01 = { version = "0.1.22", package = "tokio" }
tokio-executor = "0.1.10"
tokio-zookeeper = "0.1.3"
tracing = "0.1.29"
pin-project = "1.0.8"
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git" }

[features]
