[package]
name = "zookeeper-operator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.5"
futures = "0.3.17"
k8s-openapi = { version = "0.13.1", default-features = false, features = ["v1_22"] }
kube = { version = "0.61.0", default-features = false, features = ["derive"] }
kube-runtime = "0.61.0"
snafu = "0.6.10"
tokio = { version = "1.12.0", default-features = false, features = ["full"] }
