[package]
name = "zookeeper-operator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.5"
futures = "0.3.17"
k8s-openapi = { version = "0.13.1", default-features = false, features = ["v1_22"] }
kube = { version = "0.61.0", features = ["derive"] }
kube-runtime = "0.61.0"
schemars = "0.8.6"
semver = "1.0.4"
serde = "1.0.130"
serde_json = "1.0.68"
serde_yaml = "0.8.21"
snafu = "0.6.10"
stackable-operator = { git = "https://github.com/stackabletech/operator-rs" }
structopt = "0.3.23"
strum = "0.22.0"
strum_macros = "0.22.0"
tokio = { version = "1.12.0", features = ["full"] }
